// Mocks generated by Mockito 5.4.5 from annotations
// in ifeed/test/unit/viewmodels/local_post_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:ifeed/models/local_post_model.dart' as _i4;
import 'package:ifeed/repositories/local_post_repository.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalPostRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalPostRepository extends _i1.Mock
    implements _i2.LocalPostRepository {
  MockLocalPostRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addPost(_i4.LocalPostModel? localPost) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPost,
          [localPost],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addPosts(List<_i4.LocalPostModel>? localPosts) =>
      (super.noSuchMethod(
        Invocation.method(
          #addPosts,
          [localPosts],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.LocalPostModel>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue:
            _i3.Future<List<_i4.LocalPostModel>>.value(<_i4.LocalPostModel>[]),
      ) as _i3.Future<List<_i4.LocalPostModel>>);

  @override
  _i3.Future<_i4.LocalPostModel?> getPostById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPostById,
          [id],
        ),
        returnValue: _i3.Future<_i4.LocalPostModel?>.value(),
      ) as _i3.Future<_i4.LocalPostModel?>);

  @override
  _i3.Future<void> deletePost(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deletePost,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> editPost(
    int? id,
    _i4.LocalPostModel? localPost,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #editPost,
          [
            id,
            localPost,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
